# setup-secrets.ps1
# Description: Generates necessary secrets for the autoai project on Windows.
# Creates the .env file required by docker-compose.

param(
    [string]$DbPassword,
    [string]$RedisPassword,
    [string]$JwtSecretKey,
    [string]$EncryptionKey
)

# Function to generate a random string
function Get-RandomString {
    param(
        [int]$Length = 32
    )
    $bytes = New-Object byte[] $Length
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    # Use URL-safe Base64 encoding and remove padding
    return [System.Convert]::ToBase64String($bytes).Substring(0, $Length).Replace('+', '-').Replace('/', '_')
}

Write-Host "Generating secrets for Windows environment..."

# Create secrets directory if it doesn't exist
$secretsDir = ".\secrets"
if (-not (Test-Path -Path $secretsDir -PathType Container)) {
    New-Item -ItemType Directory -Path $secretsDir | Out-Null
}

# Generate and save secrets if they are not provided as arguments
$dbPasswordFile = Join-Path $secretsDir "db_password.txt"
if ([string]::IsNullOrEmpty($DbPassword)) {
    $DbPassword = Get-RandomString
    Set-Content -Path $dbPasswordFile -Value $DbPassword
    Write-Host "- Database password saved to $dbPasswordFile"
}

$redisPasswordFile = Join-Path $secretsDir "redis_password.txt"
if ([string]::IsNullOrEmpty($RedisPassword)) {
    $RedisPassword = Get-RandomString
    Set-Content -Path $redisPasswordFile -Value $RedisPassword
    Write-Host "- Redis password saved to $redisPasswordFile"
}

$jwtSecretKeyFile = Join-Path $secretsDir "jwt_secret_key.txt"
if ([string]::IsNullOrEmpty($JwtSecretKey)) {
    $JwtSecretKey = Get-RandomString 64 # Longer key for JWT
    Set-Content -Path $jwtSecretKeyFile -Value $JwtSecretKey
    Write-Host "- JWT secret key saved to $jwtSecretKeyFile"
}

$encryptionKeyFile = Join-Path $secretsDir "encryption_key.txt"
if ([string]::IsNullOrEmpty($EncryptionKey)) {
    $EncryptionKey = Get-RandomString 32
    Set-Content -Path $encryptionKeyFile -Value $EncryptionKey
    Write-Host "- Encryption key saved to $encryptionKeyFile"
}


# --- .env file generation ---
Write-Host "Creating/updating .env file..."

# Get absolute path for compose file paths
$currentDir = $PWD.Path
$projectRoot = Convert-Path $currentDir

$envContent = @"
# .env file for docker-compose
# This file is auto-generated by setup-secrets.ps1

# Backend settings
DB_PASSWORD=${DbPassword}
REDIS_PASSWORD=${RedisPassword}
JWT_SECRET_KEY=${JwtSecretKey}
ENCRYPTION_KEY=${EncryptionKey}
FLASK_APP=app.py
FLASK_ENV=development
DATABASE_URL=postgresql://postgres:${DbPassword}@db:5432/autoai
REDIS_URL=redis://:${RedisPassword}@redis:6379/0

# Docker-specific settings
COMPOSE_PROJECT_NAME=autoai
PROJECT_ROOT=${projectRoot}
"@

Set-Content -Path ".\.env" -Value $envContent

Write-Host ".env file has been successfully created."
Write-Host "You can now run 'docker-compose up --build -d'"
